# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra/k8s/fastapi-k8s.yaml
  - infra/k8s/fastapi-monitor.yaml

images:
  - name: pigashit/audiophile-backend 
    newName: pigashit/audiophile-backend
    newTag: "12de3fa3a8f8258ad610561c9558f12941e0eb8c"
