# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra/k8s/fastapi-k8s.yaml
  - infra/k8s/fastapi-monitor.yaml

images:
  - name: pigashit/audiophile-backend 
    newName: pigashit/audiophile-backend
    newTag: "1755cc666b89f25d063b2310bb3d158217e98315"
